version: '3.7'
services:
  zk1:
    container_name: zookeeper1
    image: wurstmeister/zookeeper:latest
    restart: always
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181
    volumes:
#      - "~/zk-cluster/zk1/data:/data"
      - "/Users/kjh/zk-cluster/zk1/data:/data"

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:latest
    restart: on-failure
    depends_on:
      - zk1
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
#      BOOTSTRAP_SERVERS: localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
